version: '3'
services:
  db:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks: 
      - default
    ports:
      - 3307:3306
    volumes:
      - ./mysql_db_data_container:/var/lib/mysql

  mongodb:
    image: mongo:4
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data_container:/data/db

  service-patient:
    image: image-patient
    container_name: container-patient
    depends_on:
      - db
    networks:
      - default
    ports:
      - 8081:8081
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mediscreen?createDatabaseIfNotExist=true"
      - "spring_datasource_username=root"
      - "spring_datasource_password=root"

  service-note:
    image: image-note
    container_name: container-note
    depends_on:
      - mongodb
    networks:
      - default
    ports:
      - 8082:8082
    environment: 
      - "SPRING_DATA_MONGODB_HOST=mongodb"

  service-rapport:
    image: image-rapport
    container_name: container-rapport
    networks:
      - default
    ports:
      - 8083:8083
    depends_on:
      - service-patient
      - service-note
    environment:
      - "patient_url=http://container-patient:8081"
      - "notes_url=http://container-note:8082"

  front:
    depends_on:
      - service-patient
      - service-note
      - service-rapport
    image: image-front
    container_name: service-front
    ports:
      - "8080:80"
    networks:
      - default